# Host: vajra - NixOS system configuration
{
  config,
  pkgs,
  vars,
  ...
}:
{
  # TODO: Import hardware-configuration.nix from your NixOS install
  imports = [
    ./hardware-configuration.nix
    ./virtualisation.nix
    #    ./paperclip.nix
    ../../modules/nixos/tailscale.nix
  ];

  # Enable Tailscale VPN
  services.tailscale-vpn.enable = true;

  users.users.${vars.os_user} = {
    isNormalUser = true;
    createHome = true;
    home = "/home/${vars.os_user}";
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "audio"
      "docker"
    ];
    shell = pkgs.nushell;
  };

  environment.systemPackages = with pkgs; [
    home-manager
    bash
  ];

  # NVIDIA drivers for GTX 1650 Mobile (Turing, TU117)
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.nvidia = {
    modesetting.enable = true;
    open = false;
    nvidiaSettings = false;
    package = config.boot.kernelPackages.nvidiaPackages.stable;
  };

  # Ollama
  services.ollama = {
    enable = true;
    host = "0.0.0.0";
    openFirewall = true;
    package = pkgs.ollama-cuda;
    environmentVariables = {
      OLLAMA_FLASH_ATTENTION = "1";
      OLLAMA_KV_CACHE_TYPE = "q8_0";
    };
  };

  # Syncthing
  services.syncthing = {
    enable = true;
    user = vars.os_user;
    group = "users";
    dataDir = "/home/${vars.os_user}/Sync";
    configDir = "/home/${vars.os_user}/.config/syncthing";
    openDefaultPorts = true;
    guiAddress = "0.0.0.0:8384";
  };

  # 2TB SSD mount
  fileSystems."/mnt/storage" = {
    device = "/dev/disk/by-uuid/aa954c90-1483-4aa2-8819-da72d5fc67ed";
    fsType = "ext4";
    options = [ "defaults" "nofail" ];
  };

  systemd.tmpfiles.rules = [
    "d /mnt/storage 0755 ${vars.os_user} users -"
  ];

  # Enable networking
  networking = {
    hostName = "vajra";
    networkmanager.enable = true;
    firewall.allowedTCPPorts = [
      2828
      8384
    ];
  };

  # Boot loader - adjust for your system
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # TODO: Replace with your actual hardware-configuration.nix
  # Generated by nixos-generate-config on your vajra laptop.
  # For now, a minimal placeholder to pass evaluation:
  # fileSystems."/" = {
  #    device = "/dev/disk/by-label/nixos";
  #    fsType = "ext4";
  # };

  # Enable nix-ld for running unpatched binaries
  programs.nix-ld.enable = true;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;
    };
  };

  # Server mode: ignore lid close, disable sleep/hibernate
  services.logind.settings.Login = {
    HandleLidSwitch = "ignore";
    HandleLidSwitchExternalPower = "ignore";
    HandleLidSwitchDocked = "ignore";
    HandleSuspendKey = "ignore";
    HandleHibernateKey = "ignore";
    IdleAction = "ignore";
  };

  systemd.targets = {
    sleep.enable = false;
    suspend.enable = false;
    hibernate.enable = false;
    hybrid-sleep.enable = false;
  };

  system.stateVersion = "24.11";
}
