# Host: vajra - NixOS system configuration
{
  pkgs,
  vars,
  ...
}:
{
  # TODO: Import hardware-configuration.nix from your NixOS install
  imports = [
    ./hardware-configuration.nix
    ./virtualisation.nix
    #    ./paperclip.nix
    ../../modules/nixos/tailscale.nix
  ];

  # Enable Tailscale VPN
  services.tailscale-vpn.enable = true;

  users.users.${vars.os_user} = {
    isNormalUser = true;
    createHome = true;
    home = "/home/${vars.os_user}";
    extraGroups = [
      "wheel"
      "networkmanager"
      "video"
      "audio"
      "docker"
    ];
    shell = pkgs.nushell;
  };

  environment.systemPackages = with pkgs; [
    home-manager
  ];

  # Syncthing
  services.syncthing = {
    enable = true;
    user = vars.os_user;
    group = "users";
    dataDir = "/home/${vars.os_user}/Sync";
    configDir = "/home/${vars.os_user}/.config/syncthing";
    openDefaultPorts = true;
  };

  # Enable networking
  networking = {
    hostName = "vajra";
    networkmanager.enable = true;
    firewall.allowedTCPPorts = [
      2828
      8384
    ];
  };

  # Boot loader - adjust for your system
  boot.loader.systemd-boot.enable = true;
  boot.loader.efi.canTouchEfiVariables = true;

  # TODO: Replace with your actual hardware-configuration.nix
  # Generated by nixos-generate-config on your vajra laptop.
  # For now, a minimal placeholder to pass evaluation:
  # fileSystems."/" = {
  #    device = "/dev/disk/by-label/nixos";
  #    fsType = "ext4";
  # };

  # Enable nix-ld for running unpatched binaries
  programs.nix-ld.enable = true;

  services.openssh = {
    enable = true;
    settings = {
      PasswordAuthentication = true;
    };
  };

  # Server mode: ignore lid close, disable sleep/hibernate
  services.logind.settings.Login = {
    HandleLidSwitch = "ignore";
    HandleLidSwitchExternalPower = "ignore";
    HandleLidSwitchDocked = "ignore";
    HandleSuspendKey = "ignore";
    HandleHibernateKey = "ignore";
    IdleAction = "ignore";
  };

  systemd.targets = {
    sleep.enable = false;
    suspend.enable = false;
    hibernate.enable = false;
    hybrid-sleep.enable = false;
  };

  system.stateVersion = "24.11";
}
